apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: {{ include "devops-task-platform.fullname" . }}
  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "devops-task-platform.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}

  endpoints:
    - port: http
      path: /metrics
      interval: 15s

      